# Assignment No 3  (Hypothesis Testing)

 Q1.A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.


In [1]:
import pandas as pd 
import numpy as np
from scipy.stats import ttest_ind

In [2]:
data=pd.read_csv(r"C:\Users\Tejasvi\Downloads\Cutlets.csv")

In [3]:
data

Unit A  Unit B
0   6.8090  6.7703
1   6.4376  7.5093
2   6.9157  6.7300
3   7.3012  6.7878
4   7.4488  7.1522
5   7.3871  6.8110
6   6.8755  7.2212
7   7.0621  6.6606
8   6.6840  7.2402
9   6.8236  7.0503
10  7.3930  6.8810
11  7.5169  7.4059
12  6.9246  6.7652
13  6.9256  6.0380
14  6.5797  7.1581
15  6.8394  7.0240
16  6.5970  6.6672
17  7.2705  7.4314
18  7.2828  7.3070
19  7.3495  6.7478
20  6.9438  6.8889
21  7.1560  7.4220
22  6.5341  6.5217
23  7.2854  7.1688
24  6.9952  6.7594
25  6.8568  6.9399
26  7.2163  7.0133
27  6.6801  6.9182
28  6.9431  6.3346
29  7.0852  7.5459
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

In [4]:
UnitA=pd.Series(data.iloc[:,0])
UnitA

0     6.8090
1     6.4376
2     6.9157
3     7.3012
4     7.4488
5     7.3871
6     6.8755
7     7.0621
8     6.6840
9     6.8236
10    7.3930
11    7.5169
12    6.9246
13    6.9256
14    6.5797
15    6.8394
16    6.5970
17    7.2705
18    7.2828
19    7.3495
20    6.9438
21    7.1560
22    6.5341
23    7.2854
24    6.9952
25    6.8568
26    7.2163
27    6.6801
28    6.9431
29    7.0852
30    6.7794
31    7.2783
32    7.1561
33    7.3943
34    6.9405
Name: Unit A, dtype: float64

In [5]:
UnitB=pd.Series(data.iloc[:,1])
UnitB

0     6.7703
1     7.5093
2     6.7300
3     6.7878
4     7.1522
5     6.8110
6     7.2212
7     6.6606
8     7.2402
9     7.0503
10    6.8810
11    7.4059
12    6.7652
13    6.0380
14    7.1581
15    7.0240
16    6.6672
17    7.4314
18    7.3070
19    6.7478
20    6.8889
21    7.4220
22    6.5217
23    7.1688
24    6.7594
25    6.9399
26    7.0133
27    6.9182
28    6.3346
29    7.5459
30    7.0992
31    7.1180
32    6.6965
33    6.5780
34    7.3875
Name: Unit B, dtype: float64

Null Hypothesis Ho:There is no significant difference in the diameter of the cutlet between two units. 
Alternate Hypothesis H1:There is a significant difference in the diameter of the cutlet between two units. Here we use two  sample t test .

In [6]:
statistic,pvalue=ttest_ind(UnitA,UnitB)
print("statistic value is {} \npvalue is {}".format(statistic,pvalue))

statistic value is 0.7228688704678063 
pvalue is 0.4722394724599501


Comparing pvalue with 5% significance level. Since pvalue>0.05, therefore we accept the null hypothesis means there is no significant difference in the diameter of the cutlet between two units.

Q2.A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.
   
  Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.
 


In [16]:
import pandas as pd 
from scipy.stats import f_oneway

In [17]:
data1=pd.read_csv(r"C:\Users\Tejasvi\Downloads\LabTAT.csv")

In [18]:
data1

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [19]:
Laboratory1=pd.Series(data1.iloc[:,0])
Laboratory1

0      185.35
1      170.49
2      192.77
3      177.33
4      193.41
        ...  
115    178.49
116    176.08
117    202.48
118    182.40
119    182.09
Name: Laboratory 1, Length: 120, dtype: float64

In [20]:
Laboratory2=pd.Series(data1.iloc[:,1])
Laboratory2

0      165.53
1      185.91
2      194.92
3      183.00
4      169.57
        ...  
115    170.66
116    183.98
117    174.54
118    197.18
119    215.17
Name: Laboratory 2, Length: 120, dtype: float64

In [21]:
Laboratory3=pd.Series(data1.iloc[:,2])
Laboratory3

0      176.70
1      198.45
2      201.23
3      199.61
4      204.63
        ...  
115    193.80
116    215.25
117    203.99
118    194.52
119    221.49
Name: Laboratory 3, Length: 120, dtype: float64

In [22]:
Laboratory4=pd.Series(data1.iloc[:,3])
Laboratory4

0      166.13
1      160.79
2      185.18
3      176.42
4      152.60
        ...  
115    172.68
116    177.64
117    170.27
118    150.87
119    162.21
Name: Laboratory 4, Length: 120, dtype: float64

Null Hypothesis Ho:There is no difference in the average Turn Around Time(TAT) among the different laboratories. Alternate Hypothesis H1:There is a difference in the average Turn Around Time(TAT) among the different laboratories. Here Anova Test is applicable-For more than two samples.

In [23]:
statistic,pvalue=f_oneway(Laboratory1,Laboratory2,Laboratory3,Laboratory4)
print("statistic value is {} \npvalue is {}".format(statistic,pvalue))

statistic value is 118.70421654401437 
pvalue is 2.1156708949992414e-57


Comparing pvalue with 5% level of significance. Here, pvalue<0.05, so We reject the null hypothesis saying that there is a difference in the average Turn Around Time(TAT) among the different laboratories.

Q3. Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions

In [24]:
df=pd.read_csv(r"C:\Users\Tejasvi\Downloads\BuyerRatio.csv")

In [25]:
df

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [26]:
df.drop(labels=['Observed Values'],axis=1,inplace=True)
df

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [29]:
Males_salesData=pd.Series(df.loc[0,'East':'South'])
Males_salesData

East      50
West     142
North    131
South     70
Name: 0, dtype: int64

In [30]:
Females_salesData=pd.Series(df.loc[1,'East':'South'])
Females_salesData

East      435
West     1523
North    1356
South     750
Name: 1, dtype: int64

Null Hypothesis Ho:All proportions are equal. V/S Alternate Hypothesis H1: Not all proportions are equal.

In [32]:
statistic,pvalue=ttest_ind(Males_salesData,Females_salesData)
print("statistic value is {} \npvalue is {}".format(statistic,pvalue))

statistic value is -3.5834877367684856 
pvalue is 0.011594334372357056


Comparing pvalue with 5% significance level.Here, pvalue<0.05, So we reject the null hypothesis saying not all proportions are equal.

Q4. TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences



In [33]:
from scipy import stats

In [35]:
datac=pd.read_csv(r"C:\Users\Tejasvi\Downloads\Costomer+OrderForm.csv")

In [36]:
datac

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [37]:
datac["Phillippines"].value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [38]:
datac["Indonesia"].value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [39]:
datac["Malta"].value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [40]:
datac["India"].value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [42]:
observations=np.array([[271,267,269,280],[29,33,31,20]])
observations

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

Null Hypothesis Ho:customer order forms defective % does not varies by center. Alternate Hypothesis H1:customer order forms defective % varies by center.

In [44]:
chi_square_score,pvalue,df,exp_table=stats.chi2_contingency(observations)
print('Chi-square score is {}.\npvalue is {}.\ndf is {}.\nExpected table is \n{}'.format(chi_square_score,pvalue,df,exp_table))

Chi-square score is 3.858960685820355.
pvalue is 0.2771020991233135.
df is 3.
Expected table is 
[[271.75 271.75 271.75 271.75]
 [ 28.25  28.25  28.25  28.25]]


Comparing p value with 5% level of significance. Here, p value> 0.05 hence we accept null hypothesis. Means customer order forms defective % varies by center.